### ISSUE TITLE
Possible to add API key to config?

### ISSUE THREAD

**Issue by trentnbauer** [deiucanta/chatpad#105]
Hi all,
Is it possible to add the OpenAI key to the config.json file?
I've tried adding it to the "defaultKey" entry but it still prompts for an API key for incognito sessions.

Thanks,

**Comment by trentnbauer** [comment]
Deleting the container and re-running my compose file has fixed this

**Comment by typoworx-de** [comment]
Can you provide your solution?

**Comment by blablazzz** [comment]
@trentnbauer can you share solution?
