### ISSUE TITLE
Usage estimate incorect

### ISSUE THREAD

**Issue by GasPoweredTomato** [deiucanta/chatpad#119]
Yesterday I had a pretty long chat with gpt 4, Chatpad is telling me it costed 7905 tokens ~ $0.01581 but when I look at the charges on open ai, it's saying I used 93,702 tokens yesterday ($2.91). Even adding up every chat I ever had with chat pad doesn't come close to 93,702 so I'm thinking the token counter might be incorrect. I have only used chatpad to use the api.

**Comment by Supernova3339** [comment]
Our math is only correct for gpt3.5-turbo
