### ISSUE TITLE
Loses API Key?

### ISSUE THREAD

**Issue by Dusky** [deiucanta/chatpad#20]
After a few prompts, the app claims to no longer have an API key, and the setting to input one no longer accepts input and is disfigured.
This persists after clearing cache, restarting the app and reinstalling. 

Strangely enough, this is only true for the one broken chat. I can start new chats as normal.

![image](https://user-images.githubusercontent.com/651254/227024732-9c5dc41b-105c-4b34-b7ae-0d4254e5b9a5.png)

**Comment by Supernova3339** [comment]
Hi Dusky, before I can solve your issue I'll need some statistics and basic information.

Are you connected to the internet ( yes/no )

If you are using a browser, what is the version and name

If you are using the browser or desktop, please open the developer console and paste any error logs.

If you are on mobile, I will need to know that.

I am waiting for your reply.

**Comment by Dusky** [comment]
Yes.
Firefox 110 (64-bit)
Desktop

![image](https://user-images.githubusercontent.com/651254/227031566-be817260-1b6a-4d6d-8e3c-33b57be2cb8d.png)

**Comment by Supernova3339** [comment]
if you use a different browser, and import your data from the previous one,
does the issue still persist?

**Comment by deiucanta** [comment]
Is that screenshot recent? Cause made some changes to the API key field today. It should look like this

![image](https://user-images.githubusercontent.com/2116280/227036110-7ea77f65-486e-4430-b096-784f73da185b.png)

**Comment by Dusky** [comment]
I've updated and now it seems to surface in a different way. It gives the flashing "thinky lines" for a long time and then eventually produces nothing.

![image](https://user-images.githubusercontent.com/651254/227042379-c531160b-1840-422f-8516-bf0a82e762b9.png)

**Comment by Dusky** [comment]
Duplicate of #12 and #20

**Comment by Supernova3339** [comment]
try clearing your data or using a different key
