### ISSUE TITLE
add support ARM64 for the docker container 

### ISSUE THREAD

**Issue by Git-Vi** [deiucanta/chatpad#26]
It would be really useful for everyone who likes self-hosted services. 
I checked, now it supports only linux/amd64
Please add possibility to use your soft for ARM64 
thank you in advance!

**Comment by suranyami** [comment]
👍

**Comment by ldgnu** [comment]
Look I found an image arm64 the test and it is working perfectly. Best regards. 
https://hub.docker.com/r/guoqiao/chatpad

**Comment by Supernova3339** [comment]
My PR adds compatibility for ARM64, just needs to be merged + a release

**Comment by Git-Vi** [comment]
Hi @Supernova3339 , any update here? Unfortunately I can't find the container with ARM64 support at dockerhub.
Thank you in advance!

**Comment by Supernova3339** [comment]
build it for arm64 yourself :)

**Comment by Supernova3339** [comment]
it's also as a github package, no dockerhub!
