### ISSUE TITLE
Bookmark chats

### ISSUE THREAD

**Issue by OctopBP** [deiucanta/chatpad#76]
I added the functionality for bookmarking chats. What do you think?

<img width="295" alt="image" src="https://github.com/deiucanta/chatpad/assets/17803104/d8f1e546-4203-4f9a-bcd1-c29d95d60ab2">

**Comment by Supernova3339** [comment]
looks awesome, PR it!

**Comment by OctopBP** [comment]
https://github.com/deiucanta/chatpad/pull/78
