### ISSUE TITLE
UI bouncing when I or chatGPT types

### ISSUE THREAD

**Issue by Yodie98** [deiucanta/chatpad#93]
Anytime I type or chatGPT is responding, the entire screen bounces. Happens on desktop and mobile in pretty much all browsers.

selfhosted on unraid. Accessing via web server

**Comment by Supernova3339** [comment]
no issues for me on the desktop app

**Comment by Yodie98** [comment]
![chatpadAI](https://github.com/deiucanta/chatpad/assets/92778277/9461e55f-7471-4b78-a680-094573ce7841)

**Comment by inv-george-karsas** [comment]
having the same problem

**Comment by Kmasterrr** [comment]
Hi @Yodie98, 

I managed to solve this by changing the ScrollIntoVew component behavior from "smooth" to "instant" 

```js
import { ReactNode } from "react";

export function ScrollIntoView({ children }: { children: ReactNode }) {
  return (
    <div
      ref={(node) => {
        if (!node) return;
        node.scrollIntoView({ behavior: "instant" });
      }}
    >
      {children}
    </div>
  );
}
```

**Comment by Eth030** [comment]
how can i fix this its unbareable

**Comment by inv-george-karsas** [comment]
hey @Eth030, 

@Kmasterrr fix below solved it for me:

> Hi @Yodie98,
> 
> I managed to solve this by changing the ScrollIntoVew component behavior from "smooth" to "instant"
> 
> ```js
> import { ReactNode } from "react";
> 
> export function ScrollIntoView({ children }: { children: ReactNode }) {
>   return (
>     <div
>       ref={(node) => {
>         if (!node) return;
>         node.scrollIntoView({ behavior: "instant" });
>       }}
>     >
>       {children}
>     </div>
>   );
> }
> ```

**Comment by cafecrema** [comment]
Same for me. Its also only in the web version. Please add this fix to the project!

**Comment by metinelitas** [comment]
Same for me for the web version

**Comment by NickBouwhuis** [comment]
I've been trying Chatpad UI for the last few months, same issue. On both the web and desktop app version.

**Comment by tvl83** [comment]
Same issue for me. It's quite annoying.
